### ISSUE TITLE
Micro-Manager interface

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/microscope#46] opened 2018-06-28 22:21 UTC
There is a micromanager python library providing acces to micromanager
https://micro-manager.org/wiki/Using_the_Micro-Manager_python_library

Would it be an idea to create a microscope wrapper to give some access to micromanager supported hardware?

J

**Comment by iandobbie** [comment] 2018-06-29 08:36
Help no!

Surely the whole point is to get away from micromanager and this will just encourage people to stay with it.

Ian

Sent from my iPhone

On 28 Jun 2018, at 23:21, juliomateoslangerak <notifications@github.com<mailto:notifications@github.com>> wrote:


There is a micromanager python library providing acces to micromanager
https://micro-manager.org/wiki/Using_the_Micro-Manager_python_library

Would it be an idea to create a microscope wrapper to give some access to micromanager supported hardware?

J

**Comment by carandraug** [comment] 2019-04-05 12:03
Closing as duplicate of issue #34

**Closed by carandraug** 2019-04-05 12:03 UTC
