### ISSUE TITLE
Outstanding hardware support

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/microscope#165] opened 2020-09-17 09:45 UTC
A list of outstanding hardware devices that we ought to support, please add more if you think we need them. 

- [ ] Boulder SLM (now meadowlark)

- [ ] Aerotech lifter

- [ ] async digitial IO, in particular the Pi but also the NI cards on OMX v2 and oxford cryosim systems. 

- [ ] PiCam

- [ ] ASI controller (as on PALM/TIRF)

- [ ] Toptica laser engine (as on PALM/TIRF)

**Comment by carandraug** [comment] 2020-09-17 11:04
> A list of outstanding hardware devices that we ought to support, please add more if you think we need them.

There will always be devices that we don't yet support, I don't think it's useful to have an issue to list them because then it will never be closed. We can have a label for new device.

>     * [ ]  Boulder SLM (now meadowlark)

Duplicate of #67

>     * [ ]  Aerotech lifter

We didn't had an issue for this, so I opened #166

>     * [ ]  async digitial IO, in particular the Pi but also the NI cards on OMX v2 and oxford cryosim systems.


We have #162 to come up with an ABC for that. We then will need to add concrete classes for the different cards.

>     * [ ]  PiCam

I've opened #167 for this.

>     * [ ]  ASI controller (as on PALM/TIRF)

Duplicate of #96 

>     * [ ]  Toptica laser engine (as on PALM/TIRF)

Duplicate of #71

**Closed by carandraug** 2020-09-17 11:04 UTC
